---
- name: Install Keystone packages
  yum: name={{ item }} state=installed enablerepo=ol7_addons,ol7_optional_latest
  with_items:
  - openstack-keystone
  - python-keystoneclient
  
- name: Configure Keystone's admin token
  ini_file: dest={{ openstack_keystone_config_file }} section=DEFAULT option=admin_token value={{ openstack_keystone_admin_token }}
  
- name: Configure Keystone's database access
  ini_file: dest={{ openstack_keystone_config_file }} section=database option=connection value=mysql://{{ openstack_keystone_db_user_name }}:{{ openstack_keystone_db_user_pass }}@{{ openstack_database_node_name }}/{{ openstack_keystone_dbname }}
  
- name: Create generic certificates and keys
  command: keystone-manage pki_setup --keystone-user {{ openstack_keystone_user_name }} --keystone-group {{ openstack_keystone_group_name }}
  
- name: Restrict access to SSL directory
  file: dest={{ openstack_keystone_log_dir }} owner={{ openstack_keystone_user_name }} group={{ openstack_keystone_group_name }}
  
- name: Restrict access to log directory
  file: dest={{ openstack_keystone_ssl_dir }} owner={{ openstack_keystone_user_name }} group={{ openstack_keystone_group_name }} mode=0750
  
- name: Populate the Identity service database
  command: keystone-manage db_sync
  
- name: Ensure permission of keystone log file
  file: name=/var/log/keystone/keystone.log owner={{ openstack_keystone_user_name }} group={{ openstack_keystone_group_name }}
  
- name: Start Openstack-Keystone service on configure on boot startup
  service: name={{ openstack_keystone_service_name }} state=started enabled=yes
  
- name: Create tenants
  os_tenant: name={{ item }} description="{{ item }} Tenant" state=present token={{ openstack_keystone_admin_token }} endpoint=http://{{ openstack_controller_node_name }}:35357/v2.0
  with_items:
    - admin
    - service
    
- name: Create admin user
  os_user: name={{ openstack_admin_tenant_admin_user }} password={{ openstack_admin_tenant_admin_pass }} email="admin@example.com" enabled=True state=present token={{ openstack_keystone_admin_token }} endpoint=http://{{ openstack_controller_node_name }}:35357/v2.0
  
- name: Create roles
  os_role: name={{ item }} state=present token={{ openstack_keystone_admin_token }} endpoint=http://{{ openstack_controller_node_name }}:35357/v2.0
  with_items:
  - admin
  - _member_
  
- name: Assign roles for user admin in tenant admin
  os_user_role: user={{ openstack_admin_tenant_admin_user }} role={{ item }} tenant=admin state=present token={{ openstack_keystone_admin_token }} endpoint=http://{{ openstack_controller_node_name }}:35357/v2.0
  with_items:
  - admin
  - _member_